-- begin PROFILES_FUNDING_APPLICATION
alter table PROFILES_FUNDING_APPLICATION add constraint FK_PROFILES_FUNDING_APPLICATION_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_PROFILES_FUNDING_APPLICATION_ON_USER on PROFILES_FUNDING_APPLICATION (USER_ID)^
-- end PROFILES_FUNDING_APPLICATION
-- begin PROFILES_PROFILE
alter table PROFILES_PROFILE add constraint FK_PROFILES_PROFILE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create unique index IDX_PROFILES_PROFILE_UNIQ_NAME on PROFILES_PROFILE (NAME)^
create index IDX_PROFILES_PROFILE_ON_USER on PROFILES_PROFILE (USER_ID)^
-- end PROFILES_PROFILE
-- begin PROFILES_PROFILE_ROLE_LINK
alter table PROFILES_PROFILE_ROLE_LINK add constraint FK_PROROL_ON_PROFILE foreign key (PROFILE_ID) references PROFILES_PROFILE(ID)^
alter table PROFILES_PROFILE_ROLE_LINK add constraint FK_PROROL_ON_ROLE foreign key (ROLE_ID) references SEC_ROLE(ID)^
-- end PROFILES_PROFILE_ROLE_LINK
